### ISSUE TITLE
form_submit event for Google Adwords

### ISSUE THREAD

**Issue by moog500nl** [formspark/examples#1]
Hi, 

I'm using formspark for Framer and I want to track a submitted form as a conversion event for Google adwords.  The problem is that when you click on an empty formspark form, using Framer, it still registers as a form_submit event. What this means is that there's no way to determine whether a form submission was successful or not. What this leads to is traffic being generated to a site using google adwords and people just sending empty form submissions leading to inflated conversion amounts in google adwords. Any advice?

**Comment by botre** [comment]
Hello, I recommend asking this question on the Framer forums: https://www.framer.community/home. Best of luck.
